env:
  commonjs: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "google"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  strict:
    - warn
    - global
  space-infix-ops:
    - warn
    - int32Hint: false
  indent:
    - error
    - 4
