env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - "eslint:recommended"
  - "google"
globals: {}
parserOptions:
  ecmaVersion: 2018
rules:
  strict:
    - warn
    - global
  space-infix-ops:
    - warn
    - int32Hint: false
  indent:
    - error
    - 4
overrides:
  - files:
    - "tests/**"
    globals:
      testing: readonly
